name: Run Test Suite

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup npm/node leveraging full caching
        uses: ./.github/setup-npm-with-caching

      - run: npm run build
      - run: npm run lint
      - run: npm run test-cjs
      - run: npm run test-esm
