name: Update cache for main branch

on:
  push:
    branches:
      - master

jobs:
  update-cache:
    if: contains(github.event.head_commit.message, 'Merge pull request')

    runs-on: ubuntu-latest

    name: Update Cache

    steps:
      - uses: actions/checkout@v4

      - name: Update cache
        uses: ./.github/setup-npm-with-caching
